name: Update PM2.5 DB

on:
  schedule:
    - cron: '10 16 * * *'  # 每天 0:10 (台灣時間)
  workflow_dispatch:       # 可手動執行

jobs:
  curl-update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Call /update-db endpoint
        run: curl -s https://pm25-project-jhxd.onrender.com/update-db